language: java

services: docker

before_install: mvn install -Dmaven.test.skip=true

install:
  - cd docker
  - ./start.sh
  - sleep 10
  - ./ps.sh
  - cd ..

script: mvn test

after_failure:
  - cd docker
  - docker-compose logs mediator-server
  - docker-compose logs mediator-client