logging.level.root: info

management.endpoints.web:
  base-path: /
  path-mapping.health: healthcheck

spring:
  http.converters.preferred-json-mapper: gson
  rabbitmq:
    username: ${BROKER_USERNAME:guest}
    password: ${BROKER_PASSWORD:guest}
    host: ${BROKER_HOST:private-mq}
    port: ${BROKER_PORT:5672}

queues: completed