version: '3.2'

networks:
  mediator_private:
    external: true
  mediator_public:
    external: true

services:

  private-mq:
    image: rabbitmq:3.6.14-management
    container_name: private-mq
    hostname: private-mq
    ports:
    - "15671:15672"
    - "5671:5672"
    networks:
    - mediator_private
    - mediator_public
    volumes:
    - ./private_mq/defs.json:/etc/rabbitmq/defs.json
    - ./private_mq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config

  mediator-server:
    image: uiobmi/mediator.server:latest
    container_name: mediator-server
    hostname: mediator-server
    ports:
    - "8080:8080"
    #    - "6006:6006"
    networks:
    - mediator_private
    - mediator_public
    environment:
    - KEYS=completed,incompleted
