logging.level.root: info

management.endpoints.web:
  base-path: /
  path-mapping.health: healthcheck

spring:
  http.converters.preferred-json-mapper: gson
  rabbitmq:
    username: ${BROKER_USERNAME:guest}
    password: ${BROKER_PASSWORD:guest}
    host: ${BROKER_HOST:public-mq}
    port: ${BROKER_PORT:5672}
    listener.simple.acknowledge-mode: manual
    listener.direct.acknowledge-mode: manual
  cloud.refresh.refreshable: none

initial-delay: ${INITIAL_DELAY:10000}

fixed-rate: ${FIXED_RATE:10000}

queues: ${QUEUES:archived,stableIDs}

mediator-server:
  listOfServers: ${MEDIATOR_SERVER:mediator-server:8080}